name: Generate Snake

on:
  push:                    
    branches:
      - master               
  schedule:               
    - cron: "0 0 * * *"
  workflow_dispatch:       


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: jfelipesouza
          outputs: |
            dist/snake.svg
            dist/snake-neon-dark.svg
          palette: |
            - color_snake: "#b100ff"       # roxo neon
              color_dot: "#000000"         # fundo preto
              color_dot0: "#000000"
              color_dot1: "#00b894"        # verde neon
              color_dot2: "#00cec9"        # ciano
              color_dot3: "#0984e3"        # azul vibrante
              color_dot4: "#6c5ce7"        # lilás neon
      - name: Push snake.svg
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
