name: Generate Snake

on:
  push:
    branches:
      - master 
  
  schedule:
    - cron: "0 0 * * *"   
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: jfelipesouza          
          
          outputs: |
            dist/snake-dracula.svg?palette=dracula         
          
          color_snake: "#BD93F9"
      
      - name: Push snake.svg
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
